### ISSUE TITLE
How do I build this on Ubuntu / Ubuntu WSL2 ?

### ISSUE THREAD

**Issue by AaronNGray** [stedolan/mlsub#8]
How do I build this on Ubuntu / Ubuntu WSL2 ?
```
$ sudo apt install ocaml
$ sudo apt install opam
$ opam install ocamlfind
$ opam install menhirLib
$ make
ocamlbuild -no-hygiene -r -cflag -bin-annot -cflag -g -lflag -g -pkg menhirLib -pkg str -use-menhir -yaccflag --explain -yaccflag --table main.byte
ocamlfind: Package `menhirLib' not found
Cannot run Ocamlfind.
make: *** [Makefile:3: all] Error 2
```

```
$ opam install menhirLib
[NOTE] Package menhirLib is already installed (current version is 20200624).
```

**Comment by nojb** [comment]
Have you done `eval $(opam config env)` to adjust your environment?

**Comment by nojb** [comment]
Also is `ocamlbuild` installed using `opam` ?

**Comment by AaronNGray** [comment]
The problem with the WSL 2 version was I installed ocamlbuild from apt-get instead of opam ! And had not obviously done the eval $(opam env).

**Comment by gasche** [comment]
Ideally the `mlsub` repository would come with a `.opam` file that lists dependencies and lets one easily install them with `opam install .` (also installs the package proper) or `opam install . --deps-only`.
